### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by bytebuddha** [xi-frontend/xrl#11]
When should we think about another crates.io Release

**Comment by little-dude** [comment]
Agree. Should this be a 0.1 ?

**Comment by bytebuddha** [comment]
No i think 0.0.5 would be best. I Think in the future Xrl should try to match google/xi-core release number's(way in the future) and keeping under 0.0 for now would give us more options later.

**Comment by little-dude** [comment]
Done! https://crates.io/crates/xrl
