### ISSUE TITLE
Update Tokio

### ISSUE THREAD

**Issue by bytebuddha** [xi-frontend/xrl#13]
I plan to start continuing work soon, and the first thing we should do is try to move away from the 'tokio-io' and 'tokio-core' crates. Tokio has been in a lot of flux lately but i think it's settled down enough to begin updating Xrl. The only tricky part will be the new reactor require's the Send trait be implemented on all futures, even still i should have a PR with this sometime next week.

**Comment by little-dude** [comment]
Nice ! :+1:
