### ISSUE TITLE
Incoperating into more frontends

### ISSUE THREAD

**Issue by Cogitri** [xi-frontend/xrl#23]
Hey there,

I'm the author of [gxi](https://github.com/Cogitri/gxi). I've just split up gxi into more crates a bit ago, but then stumbled on this. Is there still interest in this? If so, I'd very much like to help here - a shared implementation would be amazing!

Current problems I see with using xrl in gxi (please do point mistakes on my side out here):

* gxi is currently structured like this:

![image](https://user-images.githubusercontent.com/8766773/58327235-5bc96a00-7e2f-11e9-90f6-a99007d9d734.png)

Everything themed black is the `MainWin`, which holds `EditView`s (everything that's white, basically the editing area). The `MainWin` takes care of the general state: It receives notifications by Xi-editor and sends _some_ of them to the EditView (See https://github.com/Cogitri/gxi/blob/master/src/gxi/src/main_win.rs#L357. Some notifications are handled by the `MainWin` (e.g. `alert`/`available_themes`), others are sent to the respective EditView as set by the `view-id` that is contained in the message (e.g. `update`/`scroll_to`). Both `MainWin` and all `EditViews` hold one (refcounted) `MainState` which sets (as the name suggests)  some settings across all views, such as the config, theme etc. About everything in gxi is refcounted due to GTK objects being refcounted too. This means that in Frontend::update I wouldn't need to pass in a `&mut self` of the MainWin, but instead would use a `&self` reference of MainWin and get the current EditView (https://github.com/Cogitri/gxi/blob/master/src/gxi/src/main_win.rs#L749).

This doesn't seem to fit too well into xrl's concept of the Frontend Trait.

**Comment by Cogitri** [comment]
I guess this makes it sort of related to #22 

Hope what I wrote was somewhat easy to understand, I should really document gxi better

**Comment by bytebuddha** [comment]
Hey thanks for the interest. I'd very much like to see xrl used by as many frontend's as possible and would help you in any way that i can. For you to use the frontend trait with GTK that would require a sync channel of some kind, something like `std::sync::mpsc::channel` you could then create a frontend struct that forwards events from xi-core through the channel. You would then have to run the tokio reactor in a different thread using `thread::spawn`
```
pub struct Frontend(Sender<T>);

impl Frontend {
 ...
}
```
The other end of the channel can be placed in your MainWin struct and you could fetch the events appropriately from GTK's event loop. But XRL is based on the Tokio event loop and IIRC GTK has to use it's own event loop, if thats the case i think it would make more sense to not use the frontend trait and use XRL for serializing/deserializing & you could use the line cache struct as well.

**Comment by Cogitri** [comment]
> But XRL is based on the Tokio event loop and IIRC GTK has to use it's own event loop

Maybe we could add a glib based event loop, will look into that.

> you could use the line cache struct as well.

Yup, let's see how I can merge gxi's current implementation and xrls. Will work on this tomorrow then :)

**Comment by bytebuddha** [comment]
A glib based event loop would be nice. Im not sure how easy it would be to make that work, but i know [relm](https://github.com/antoyo/relm) integrates tokio and GTK, so it must be somewhat possible.

If there's anything i can do to help please let me know

**Comment by Cogitri** [comment]
Alright, so I've just looked into this. How well does using the system instance of xi-editor work for you? Right now in gxi I just build xi-editor's core-lib into gxi and [start it on another thread](https://github.com/Cogitri/gxi/blob/master/src/gxi-peer/src/xi_thread.rs#L26), [which I later listen on for messages](https://github.com/Cogitri/gxi/blob/master/src/gxi-peer/src/rpc.rs#L59). I personally prefer this approach to not depend on foreign binaries (and also comes with the advantage that gxi is tested against one specific xi-editor version), but I suppose I wouldn't mind using xrl's approach either.

**Comment by bytebuddha** [comment]
It works pretty well. Your correct we just inform people to make sure `xi-core` is installed in $PATH, But i think xrl should be able to use both ways.  A long time ago i was pondering creating a XiCore trait with 2 implementations `SystemXi` and `CoreLib` that would allow using xi however you wish but i never got around to implementing it. WOuld you have a better idea on how to implement it?

**Comment by Cogitri** [comment]
Hm, I would've done that by using features, like this:

```
+[features]
+
+# Run a xi-editor binary in a tokio based eventloop
+default = ["eventloop"]
+
+eventloop = ["tokio", "tokio-codev", "tokio-process"]
+
+# Run an xi-editor instance built into the binary in a seperate thread
+thread = ["xi-core-lib", "xi-rpc"]
```

And depending on what feature is chosen I'd either use the `core-external-binary` module or a `core-in-thread` (names are subject to change :P) module. This makes this a build-time setting, but that isn't much of a problem IMHO.

**Comment by Cogitri** [comment]
I guess I'll use the tokio based stuff for now in gxi and change this later on.

**Comment by Cogitri** [comment]
Alright, it compiles now with #24, but needs way more work to get back to the previous functionality. Will keep you updated once it works! :)

**Comment by Cogitri** [comment]
![Screenshot from 2019-05-27 19-38-40](https://user-images.githubusercontent.com/8766773/58433382-59794100-80b7-11e9-8476-b91126ed7150.png)

Now to clean up my mess :)

**Comment by Cogitri** [comment]
Now that gxi uses xrl I'm going to close this. I have one remaining question though: Does xi-term somehow make the linecache async, @little-dude? I'm currently having some difficulty with that in gxi. When I open big files in gxi (let's say gxi's edit_view.rs`) with syntax highlighting enabled and do something which affects lots of lines (e.g. insert a `"`, which will quote all following lines and as such Xi will re-send me all these lines with the changed styles) gxi gets stuck for a bit until all the updates are processed, which is elegy annoying (but this also happened with gxi's old linecache).
