### ISSUE TITLE
Add support for sending results to Xi

### ISSUE THREAD

**Issue by Cogitri** [xi-frontend/xrl#25]
When Xi asks us to measure the width of some strings for word wrapping, we have to send the result of that back to Xi like this:

`{"id":0, "result":[[28.0,8.0]]}`

See:
https://xi-editor.io/docs/frontend-protocol.html#measure_width

To be honest, I'm not quite sure how to add this, could you help @bytebuddha? :)

**Comment by Cogitri** [comment]
FWIW this currently looks like this in gxi: https://github.com/Cogitri/gxi/blob/master/src/gxi-peer/src/rpc.rs#L123

**Comment by Cogitri** [comment]
We'll also have to implement Service::handle_request for this.

**Comment by little-dude** [comment]
`measure_width` requests are available in 0.0.6
