### ISSUE TITLE
Compiler panics on 'cargo doc'

### ISSUE THREAD

**Issue by ytmhub** [xi-frontend/xrl#36]
Since the latest merge, it seems the compiler panics when generating docs.
I know this is probably a rustc error (as proclaimed by the compiler as well) and has nothing to do with the changes made, but I'm not familiar enough with it to properly report it in the rustc repo.

Anyway, this is what I'm getting after running cargo doc:

```error: internal compiler error: src/librustc/hir/def.rs:337: attempted .def_id() on invalid res: Err

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:638:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0-nightly (991c719a1 2019-06-08) running on x86_64-unknown-linux-gnu

error: Could not document `xrl`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-name xrl src/lib.rs --color always -o /home/ytm/gits/xrl/target/doc -L dependency=/home/ytm/gits/xrl/target/debug/deps --extern bytes=/home/ytm/gits/xrl/target/debug/deps/libbytes-f3979da2585e2f8c.rmeta --extern futures=/home/ytm/gits/xrl/target/debug/deps/libfutures-4d35d0dfb2cf9c5c.rmeta --extern log=/home/ytm/gits/xrl/target/debug/deps/liblog-57adf34c664418a7.rmeta --extern serde=/home/ytm/gits/xrl/target/debug/deps/libserde-c032e6fc1443ab71.rmeta --extern serde_derive=/home/ytm/gits/xrl/target/debug/deps/libserde_derive-ea462f6a94497eaa.so --extern serde_json=/home/ytm/gits/xrl/target/debug/deps/libserde_json-174790a96bed0ec1.rmeta --extern syntect=/home/ytm/gits/xrl/target/debug/deps/libsyntect-4b9923d54456b828.rmeta --extern tokio=/home/ytm/gits/xrl/target/debug/deps/libtokio-23628aae7aaab09a.rmeta --extern tokio_codec=/home/ytm/gits/xrl/target/debug/deps/libtokio_codec-c5bf1894fd967b98.rmeta --extern tokio_process=/home/ytm/gits/xrl/target/debug/deps/libtokio_process-c3dbf4897bc08d57.rmeta` (exit code: 1)
```

**Comment by Cogitri** [comment]
This is on Rust: https://github.com/rust-lang/rust/issues/61732

I guess I'll keep this open as sort of a tracking issue.

**Comment by AIOOB** [comment]
I'm reasonably sure it's caused by this line:
https://github.com/xi-frontend/xrl/blob/c93af615f321d38b8ee50e9ddc06b096bb68d3c0/src/protocol/client.rs#L220

I don't think that's valid rust, but truthfully I have no idea as I can't find that construction documented anywhere, and it does compile...

**Comment by Cogitri** [comment]
> I don't think that's valid rust, but truthfully I have no idea as I can't find that construction documented anywhere

https://doc.rust-lang.org/reference/visibility-and-privacy.html suggests it should be fine, but removing it does indeed fix the thing. I don't actually think we need that line anymore, or do we, @little-dude ?
